ci:
  autofix_commit_msg: |
    chore: autofixes from pre-commit

  autoupdate_commit_msg: 'chore(deps): update pre-commit dependencies'
  # We use renovate for this anyway
  autoupdate_schedule: quarterly

default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        # Removing one of the two newlines at the end of this file breaks parsing.
        exclude: packages/ynap-parsers/src/de/1822direkt/test-data/umsaetze-12345678-25.03.2020_11_45.csv
      - id: trailing-whitespace

  # Explicitly not using the renovate upstream hook because for some reason installing it is
  # excruciatingly slow (> 10 minutes in some cases)
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-renovate
