name: Publish ynap-parsers
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/ynap-parsers

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: yarn
          always-auth: true
          cache-dependency-path: yarn.lock

      - run: yarn

      - name: publish parsers
        run: |
          cd packages/ynap-bank2ynab-converter
          yarn build
          cd ../ynap-parsers
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
