name: Publish ynap-bank2ynab-converter
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/ynap-bank2ynab-converter

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: yarn
          always-auth: true
          cache-dependency-path: yarn.lock

      - run: yarn

      - name: publish bank2-ynab-converter
        run: |
          cd packages/ynap-bank2ynab-converter
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
