name: Publish ynap-parsers
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/ynap-parsers/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: npm
          always-auth: true
          cache-dependency-path: package-lock.json

      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: publish parsers
        run: |
          cd packages/ynap-bank2ynab-converter
          npm run build
          cd ../ynap-parsers
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
