name: Publish package to GitHub Packages
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: yarn
          always-auth: true
          cache-dependency-path: yarn.lock

      - run: yarn

      - name: publish bank2-ynab-converter
        run: |
          cd packages/ynap-bank2ynab-converter
          yarn prepublishOnly
          yarn publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish parsers
        run: |
          cd packages/ynap-bank2ynab-converter
          yarn prepublishOnly
          cd ../ynap-parsers
          yarn prepublishOnly
          yarn publish --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
