name: Publish ynap-parsers
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/ynap-parsers/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
          always-auth: true
          cache-dependency-path: package-lock.json

      - run: npm install

      - name: publish parsers
        run: |
          cd packages/ynap-bank2ynab-converter
          npm run build
          cd ../ynap-parsers
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
