name: Publish ynap-bank2ynab-converter
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/ynap-bank2ynab-converter/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: npm
          always-auth: true
          cache-dependency-path: package-lock.json

      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish bank2-ynab-converter
        run: |
          cd packages/ynap-bank2ynab-converter
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
