name: 'Check version bump for parsers'

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/ynap-parsers/**

jobs:
  version-bump:
    permissions:
      contents: read
      packages: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Get the latest published version from the registry
        run: echo version=$(npm view @envelope-zero/ynap-parsers --json | jq -r .version) >> $GITHUB_OUTPUT
        id: published
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo version=$(cat packages/ynap-parsers/package.json | jq -r .version) >> $GITHUB_OUTPUT
        id: new

      - uses: madhead/semver-utils@36d1e0ed361bd7b4b77665de8093092eaeabe6ba # v4.3.0
        id: comparison
        with:
          version: ${{ steps.new.outputs.version }}
          compare-to: ${{ steps.published.outputs.version }}

      - name: Verify that version is bumped
        run: |
          if [[ ">" != "${{ steps.comparison.outputs.comparison-result }}" ]]; then
            echo "::error::The package version needs to be bumped when making changes in the module" && exit 1
          fi
