name: 'Check version bump for bank2ynab-converter'

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/ynap-bank2ynab-converter/**

jobs:
  version-bump:
    permissions:
      contents: read
      packages: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Get the latest published version from the registry
        run: echo version=$(npm view @envelope-zero/ynap-bank2ynab-converter --json | jq -r .version) >> $GITHUB_OUTPUT
        id: published
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo version=$(cat packages/ynap-bank2ynab-converter/package.json | jq -r .version) >> $GITHUB_OUTPUT
        id: new

      - uses: madhead/semver-utils@ed58b1e544d13426a67fea39cb19638b3c5623d4 # v4.0.0
        id: comparison
        with:
          version: ${{ steps.new.outputs.version }}
          compare-to: ${{ steps.published.outputs.version }}

      - name: Verify that version is bumped
        run: |
          if [[ ">" != "${{ steps.comparison.outputs.comparison-result }}" ]]; then
            echo "::error::The package version needs to be bumped when making changes in the module" && exit 1
          fi
